### ISSUE TITLE
Even after specifiying output directory, no coverage data is shown

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [shanbin/scoverage-plugin#13]
I specify `servision/target/scoverage-report` as the scoverage report directory and `scoverage.xml` as the scoverage report file.

In this directory, I can see an `index.html` that is viewable with a browser.

But the link the plugin creates in the Jenkins project page,shows empty content.
I think this is a bug.

Using latest version: 1.3.0 and Jenkins 1.651

**Comment by shanbin** [comment]
Which build tool is being used?

**Comment by DavidPerezIngeniero** [comment]
Of course SBT and scoverage-plugin version 1.3.0.

**Comment by shanbin** [comment]
Should be a duplicate of #15
