### ISSUE TITLE
make it all green if coverage is 100%

### ISSUE THREAD

**Issue by jozic** [shanbin/scoverage-plugin#19]
at the moment if coverage 100%, it still shows some red

![image](https://cloud.githubusercontent.com/assets/124249/21202225/07ab07d4-c21c-11e6-8134-b81c1c0e558f.png)

Could we have it all green?
Thanks

**Comment by shanbin** [comment]
Fixed in b8ec6a48a0cd781787aa8063913d09630cd2f6e2 as version 1.3.2
