### ISSUE TITLE
Graph is empty with a multimodule project

### ISSUE THREAD

**Issue by YannMoisan** [shanbin/scoverage-plugin#2]
I know that merged reports are not yet supported but I just want to display one.

In the console, i see : 

08:55:26 [info] [scoverage] Generating XML report [/scratch/jenkins/workspace/[myproject] - coverage/[mymodule]/target/scala-2.10/scoverage-report/scoverage.xml]
So scoverage config seems ok.

I tried to configure Scoverage Report Directory with the following values
- scoverage-report
- **/scoverage-report
- coverage/[mymodule]/target/scala-2.10/scoverage-report

Any idea ?

**Comment by gurmeetsaran** [comment]
@shanbin @YannMoisan - for some reason even after specifying full directory path. it is not working for me and I am seeing empty graph.

**Comment by gurmeetsaran** [comment]
@shanbin @YannMoisan - my bad. I was pointing to wrong directory

**Comment by shanbin** [comment]
Multi-module is natively supported by scoverage, closed this for now.
