### ISSUE TITLE
Jenking Pipeline support

### ISSUE THREAD

**Issue by nemo83** [shanbin/scoverage-plugin#23]
Hi,

I don't seem to be able to find Jenkins Pipeline support for publishing scoverage reports. 

Am I missing something?

Thanks,
Gio

**Comment by nemo83** [comment]
Right, so I was wrong, but it may be help to add 1-liner to the documentation on how to use this with Pipeline!!

`step([$class: 'ScoveragePublisher', reportDir: 'target/scala-2.11/scoverage-report', reportFile: 'scoverage.xml'])`

**Comment by shanbin** [comment]
Thanks! Doc is updated on https://wiki.jenkins.io/display/JENKINS/Scoverage+Plugin
