### ISSUE TITLE
'stapler-class' is deprecated

### ISSUE THREAD

**Issue by aioue** [shanbin/scoverage-plugin#5]
Log warning:

```WARNING org.kohsuke.stapler.RequestImpl$TypePair convertJSON
'stapler-class' is deprecated: org.jenkinsci.plugins.scoverage.ScoveragePublisher```

scoverage 1.1.1
jenkins 1.601

**Comment by shanbin** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-27918

We will upgrade to a newer version of Jenkins LTS release to "fix" this warning.

**Comment by shanbin** [comment]
Should be less annoying in the latest 1.3.0 version.
