### ISSUE TITLE
Clicking on coverage graph from jenkins job summary page results in 404

### ISSUE THREAD

**Issue by droy-shutterstock** [shanbin/scoverage-plugin#6]
My maven project is using scoverage plugin 1.1.0.
Produces following in target:
![tree](https://cloud.githubusercontent.com/assets/13023109/8316098/bc4e1252-19c2-11e5-8627-aeb63bce108e.jpg)

Jenkins config as follows:

![jenkins](https://cloud.githubusercontent.com/assets/13023109/8316143/0acdacbc-19c3-11e5-9416-cd01ee0a5b9f.jpg)

Jenkins shows the accurate chart from scoverage however, Clicking the html report leads to 404 similar to https://github.com/shanbin/scoverage-plugin/issues/4

**Comment by droy-shutterstock** [comment]
It seems the html files are not getting copied to the jenkins server from the build node. Copying them manually inside a scoverage-report folder seems to work for a build.

**Comment by thisismana** [comment]
Have you found a more robust (automatic) solution for this issue?

**Comment by shanbin** [comment]
Should be fixed in the latest 1.2.1.
